__title__ = 'dj-rest-auth'
__description__ = 'Authentication and Registration in Django Rest Framework.'
__url__ = 'http://github.com/Solidangle-net/dj-rest-auth'
__version__ = '5.0.1'
__author__ = '@vecchp https://github.com/Solidangle-net'
__author_email__ = 'imichael@pm.me'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 @vecchp https://github.com/Solidangle-net'
